import jsPDF from "jspdf";
import { UserOptions } from "jspdf-autotable";

/**
 * Shared PDF styling for ExpenseWaale exports.
 * Warm palette (terracotta + sage), tuned for white paper.
 */

export type RGB = [number, number, number];

export const PDF_COLORS = {
  primary: [159, 79, 45] as RGB,        // terracotta — HSL(18 75% 40%)
  primaryDark: [127, 63, 36] as RGB,
  accent: [98, 134, 45] as RGB,          // sage — HSL(84 50% 35%)
  text: [41, 37, 36] as RGB,             // warm near-black
  textMuted: [120, 113, 108] as RGB,
  surface: [255, 255, 255] as RGB,
  surfaceAlt: [252, 248, 242] as RGB,    // cream tint
  border: [225, 220, 213] as RGB,
  positive: [98, 134, 45] as RGB,
  negative: [185, 28, 28] as RGB,
  highlight: [254, 243, 199] as RGB,     // soft warm yellow for callouts
};

const FONT = "helvetica";

export interface PdfHeaderOptions {
  title: string;
  subtitle?: string;
  meta?: string;
}

/** Draws the branded header bar. Returns the Y coordinate where content should begin. */
export const drawPdfHeader = (doc: jsPDF, opts: PdfHeaderOptions): number => {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...PDF_COLORS.primary);
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont(FONT, "bold");
  doc.setFontSize(19);
  doc.text(opts.title, 14, 15);

  if (opts.subtitle) {
    doc.setFont(FONT, "normal");
    doc.setFontSize(10.5);
    doc.text(opts.subtitle, 14, 23);
  }

  if (opts.meta) {
    doc.setFont(FONT, "normal");
    doc.setFontSize(9);
    const w = doc.getTextWidth(opts.meta);
    doc.text(opts.meta, pageWidth - 14 - w, 23);
  }

  return 40;
};

/** Footer drawn on a single page. For multi-page tables, autoTable's didDrawPage hook calls this. */
export const drawPdfFooter = (doc: jsPDF): void => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageCount = doc.getNumberOfPages();
  const currentPage = doc.getCurrentPageInfo().pageNumber;

  doc.setFont(FONT, "normal");
  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.textMuted);

  const brand = "Generated by ExpenseWaale";
  const brandW = doc.getTextWidth(brand);
  doc.text(brand, (pageWidth - brandW) / 2, pageHeight - 8);

  if (pageCount > 1) {
    const pg = `Page ${currentPage} of ${pageCount}`;
    const pgW = doc.getTextWidth(pg);
    doc.text(pg, pageWidth - 14 - pgW, pageHeight - 8);
  }
};

/** Section title above a table or callout. Returns next Y. */
export const drawSectionTitle = (doc: jsPDF, text: string, y: number): number => {
  doc.setFont(FONT, "bold");
  doc.setFontSize(13);
  doc.setTextColor(...PDF_COLORS.text);
  doc.text(text, 14, y);
  return y + 6;
};

/** Body paragraph (e.g. summary lines). Returns next Y. */
export const drawBody = (
  doc: jsPDF,
  text: string,
  y: number,
  opts: { size?: number; muted?: boolean } = {}
): number => {
  doc.setFont(FONT, "normal");
  doc.setFontSize(opts.size ?? 10);
  doc.setTextColor(...(opts.muted ? PDF_COLORS.textMuted : PDF_COLORS.text));
  doc.text(text, 14, y);
  return y + (opts.size ? opts.size * 0.6 : 6);
};

/** Default table styling — primary terracotta headers, cream alternate rows. */
export const tableStyles = (overrides: Partial<UserOptions> = {}): UserOptions => ({
  theme: "grid",
  styles: {
    font: FONT,
    fontSize: 9,
    cellPadding: 3,
    textColor: PDF_COLORS.text,
    lineColor: PDF_COLORS.border,
    lineWidth: 0.1,
  },
  headStyles: {
    fillColor: PDF_COLORS.primary,
    textColor: [255, 255, 255],
    fontStyle: "bold",
    fontSize: 10,
    halign: "left",
  },
  alternateRowStyles: {
    fillColor: PDF_COLORS.surfaceAlt,
  },
  margin: { left: 14, right: 14, bottom: 16 },
  ...overrides,
});

/** Sage-headed table — used for "settlements" or "positive outcome" tables. */
export const accentTableStyles = (
  overrides: Partial<UserOptions> = {}
): UserOptions =>
  tableStyles({
    headStyles: {
      fillColor: PDF_COLORS.accent,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
      halign: "left",
    },
    ...overrides,
  });

/** Convenience: build a fresh A4 jsPDF document. */
export const createPdfDoc = (): jsPDF =>
  new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
